### ISSUE TITLE
Deploy `open.aragonpm.eth` to staging

### ISSUE THREAD

**Issue by sohkai** [aragon/deployments#54]
As well as document where it is on other environments (e.g. rinkeby and mainnet).

**Comment by 0xGabi** [comment]
@sohkai  @izqui Let me know if I can help with the deployment. 

Would be cool to have this registry so we can include a new environment on the boilerplates for staging. In the meantime, we can configure the Rinkeby ENS and use `placeholder-app-name-staging` as appName

**Comment by sohkai** [comment]
Probably best if @izqui does it so he gets the root permissions in the created aragonPM instance. It should be really quick to do (exactly the same as the other `open.aragonpm.eth`s; no point fixing the internal appIds for now); we just need to do it :).
