### ISSUE TITLE
Document ppf deployment on rinkeby and mainnet

### ISSUE THREAD

**Issue by sohkai** [aragon/deployments#55]

**Comment by izqui** [comment]
Will redeploy it with a newer compiler version to both networks

**Comment by sohkai** [comment]
Maybe if we meant to use proxies on top of it (which may make sense), otherwise the "default" one would be A1's?

**Comment by izqui** [comment]
I was thinking `ppf-factory.aragonpm.eth` for factory and then `ppf-a1.aragonpm.eth` (it would be even better if we got an `a1.aragonpm.eth` registry for us actually!)

**Comment by sohkai** [comment]
I like both of those (`ppf-factory.aragonpm.eth` and `a1.aragonpm.eth`) ❤️
