### ISSUE TITLE
Publish Agent app without irrelevant file and include metadata

### ISSUE THREAD

**Issue by 0xGabi** [aragon/deployments#91]
The Agent app IPFS content was published with a lot of irrelevant files. As [viewed here](https://ipfs.eth.aragon.network/ipfs/QmT2c6ffZ5e9vbQiQdWyRjZAxY9cMmZYNBEDW4Ne4dm2RG).

We could use the same command as in the Vault app and include the relevant metadata at the same time (https://github.com/aragon/aragon-apps/pull/880):

`aragon apm publish patch --environment mainnet --files public`

**Comment by 0xGabi** [comment]
In a similar fashion should we deploy `dao-templates` only with the `manifest.json`?

`aragon apm publish patch --files manifest.jso`

**Comment by sohkai** [comment]
@0xGabi does the CLI not include the `manifest.json` file by default? But yes, we should minimize the IPFS files as much as possible.

**Comment by 0xGabi** [comment]
@sohkai Yes it does. And the default value of the `--files` flag is `.` so all files are included. Using `manifest.json` instead we only include the relevant information for templates. Btw this is something I been thinking to improve for the publish workflow

**Comment by sohkai** [comment]
I think we had decided at one point earlier that we shouldn't _enforce_ the `manifest.json` as part of the publishing process, but if it's present, I think it would be reasonable to include always include it (similar to the built `artifact.json`).

However, that does bring up the question of if there's a way for a user to specify that they don't want any other files to be published.

**Comment by sohkai** [comment]
This has been done as part of the 0.8 release.
